
#import <UIKit/UIKit.h>

#import <OpenGLES/ES2/gl.h>
#import <OpenGLES/ES2/glext.h>

@class EAGLContext;

/* This is a UIView specifically designed for bRenderer and needs to be added to a window in your project */
@interface BView : UIView {
@private
    GLint framebufferWidth;
    GLint framebufferHeight;
    
    // the time when the app was started
    double initialTime;
    
    GLuint defaultFramebuffer, colorRenderbuffer, depthRenderbuffer;
    
    // the display link is used to create a render loop
    CADisplayLink* displayLink;
    
}

/* The OpenGL context with autogenerated getter and setter */
@property (nonatomic, retain) EAGLContext *context;

/* Control the renderer from within your Objective-C code using these functions */
- (void) runRenderer;
- (void) stopRenderer;
- (void) terminateRenderer;
@end
